---
title: "Reproducible documents"
author: "Johanne Sloth Lauszus"
format: html
---

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```
## About me
- Johanne
- AU
- LMT

I am a *phd student* and I am **very** new to R

## Simple code

```{r}
3*3
```

```{r}
2+2
```

## Testing of git
I just want to test this 

## Showing the data
```{r}
post_meal_data
glimpse(post_meal_data)
```
## PLot one continuous variable

```{r}
#| message: false
#| warning: false
#| fig-cap: "Distribution of BMI."
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x=BMI))+
         geom_histogram()
```
## Exercise: discrete plots
```{r}
#| fig-cap: "Glykemi among patients"
#| label: fig-glykemi-bar
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```
See @fig-glykemi-bar above for a cool plot!

## Plotting two discrete variables

```{r}
ggplot(post_meal_data, aes(x=Group, fill=as.character(glykemi))) +
  geom_bar(position = position_dodge())
```
## side by side plots
```{r}
#| message: false
#| warning: false
#| label: fig-bmi-glycemia
#| fig-cap: "BMI and glycemia, side by side"
#| fig-subcap:
#| - "Distribution of BMI"
#| - "Number of those with glycemia" 
#| layout-ncol: 2
ggplot(post_meal_data, aes(x=BMI))+
  geom_histogram()

ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```


